Create Spinner and Improve Code
fga-eps-mds/2020.2-Projeto-Kokama-Front-end pull request #14
Opened 2021-04-10 18:19 UTC by laispa

Co-authored-by: Ana Júlia <aluzianobriceno@gmail.com>

## Descrição 

Melhoria e refatoração do Código Frontend

**Resolve a issue [#146]().

## Tarefas realizadas

 - [x]  Organizar componentes conforme já desenvolvido em screens, isto é, criar uma pasta com o nome do componente e, dentro dessa pasta, criar os arquivos styles.ts, index.tsx e interface.ts (se aplicável);
 - [x] Excluir arquivo yarn-error.log;
 - [x] Colocar no .gitignore arquivos yarn-error.log e yarn-debug.log;
 - [x] Criar component spinner (ou importar e personalizar a partir de alguma biblioteca, como o native base) que será apresentado enquanto o aplicativo recupera informações da API;
 - [ ] Refatorar componente Stories: componente muito pequeno e que provavelmente não será reutilizado, mover para a tela KokamaStories. Além disso, refatorar estilo, muitas repetições;
 - [x] Na tela Story, substituir dados mockados por props;
 - [x] Na página que apresenta as histórias do povo kokama, apresentar spinner de loading enquanto o conteúdo é recuperado do servidor;
 - [x] Corrigir problemas com folha de estilo (eslint) no código: props, variáveis e estados não utilizados; quebra de linhas, espaços brancos etc;

2021-04-10 21:43 UTC, LightZX commented
Faltam as evidências de conclusão e uma correção do sonar cloud.

2021-04-10 23:40 UTC, LightZX approved these changes
Parabéns pessoal bom trabalho!

2021-04-11 08:08 UTC, luisgaboardi commented
@laispa e @aluzianobriceno , por favor, resolvam o conflito que a branch de vocês tá dando com a dev. Com a revisão do Z e essa resolução, só vai faltar alguém de EPS aceitar o PR.

2021-04-11 08:45 UTC, luisgaboardi commented on projeto-kokama/App.tsx
> +        headerTitle: () => <TopMenu name="Histórias do povo Kokama" />,
Se possível, colocar uma distância entre o título e a tela. o Título tá muito colado (vide imagem que vocês colocaram nas evidências)

2021-04-11 17:28 UTC, laispa commented
Pronto! Ainda bem que viu o erro da Historias do Povo Kokama, ele dava na dev e eu nem tinha visto kkkkk

2021-04-12 14:12 UTC, WelisonR requested changes
Parabéns pelo trabalho, @laispa e @aluzianobriceno, muito bom!! Indiquei alguns pontos simples de melhoria. Fora isso, por favor, exclua os arquivos vazios que foram commitados:

- projeto-kokama/src/screens/Information/index.tsx
- projeto-kokama/src/screens/Information/interface.ts
- projeto-kokama/src/screens/Information/styles.ts
- projeto-kokama/src/screens/User/index.tsx
- projeto-kokama/src/screens/User/styles.ts

2021-04-12 14:12 UTC, WelisonR commented on projeto-kokama/src/components/SpinnerLoading.tsx
> +
Remover linha 7

2021-04-12 14:12 UTC, WelisonR commented on projeto-kokama/src/components/SpinnerLoading.tsx
> +                    Carregando...</Text>
Tag que fecha Text embaixo

2021-04-12 14:12 UTC, WelisonR commented on projeto-kokama/src/screens/Story/index.tsx
> +
Remover linha

2021-04-12 14:14 UTC, WelisonR commented on projeto-kokama/src/screens/Translation/index.tsx
> +
Remover linha 188

2021-04-12 20:27 UTC, merged